-- MySQL Script generated by MySQL Workbench
-- Sun Oct  4 21:25:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members` (
  `mail` CHAR(255) NOT NULL,
  `name` CHAR(255) NOT NULL,
  `expiry_date` DATE NOT NULL,
  PRIMARY KEY (`mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pool_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pool_members` (
  `members_mail` CHAR(255) NOT NULL,
  `gym_members_members_mail` CHAR(255) NOT NULL,
  INDEX `fk_gym_member_members1_idx` (`members_mail` ASC) VISIBLE,
  PRIMARY KEY (`members_mail`),
  INDEX `fk_pool_members_gym_members1_idx` (`gym_members_members_mail` ASC) VISIBLE,
  CONSTRAINT `fk_gym_member_members10`
    FOREIGN KEY (`members_mail`)
    REFERENCES `mydb`.`members` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pool_members_gym_members1`
    FOREIGN KEY (`gym_members_members_mail`)
    REFERENCES `mydb`.`gym_members` (`members_mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gym_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gym_members` (
  `members_mail` CHAR(255) NOT NULL,
  `pool_members_members_mail` CHAR(255) NOT NULL,
  INDEX `fk_gym_member_members1_idx` (`members_mail` ASC) VISIBLE,
  PRIMARY KEY (`members_mail`),
  INDEX `fk_gym_members_pool_members1_idx` (`pool_members_members_mail` ASC) VISIBLE,
  CONSTRAINT `fk_gym_member_members1`
    FOREIGN KEY (`members_mail`)
    REFERENCES `mydb`.`members` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gym_members_pool_members1`
    FOREIGN KEY (`pool_members_members_mail`)
    REFERENCES `mydb`.`pool_members` (`members_mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `mail` CHAR(255) NOT NULL,
  `name` CHAR(255) NOT NULL,
  `hours_worked` INT NOT NULL,
  PRIMARY KEY (`mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oversees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`oversees` (
  `members_mail` CHAR(255) NOT NULL,
  `staff_mail` CHAR(255) NOT NULL,
  PRIMARY KEY (`members_mail`, `staff_mail`),
  INDEX `fk_members_has_staff_staff1_idx` (`staff_mail` ASC) VISIBLE,
  INDEX `fk_members_has_staff_members_idx` (`members_mail` ASC) VISIBLE,
  CONSTRAINT `fk_members_has_staff_members`
    FOREIGN KEY (`members_mail`)
    REFERENCES `mydb`.`members` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_has_staff_staff1`
    FOREIGN KEY (`staff_mail`)
    REFERENCES `mydb`.`staff` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pool_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pool_staff` (
  `staff_mail` CHAR(255) NOT NULL,
  INDEX `fk_pool_staff_staff1_idx` (`staff_mail` ASC) VISIBLE,
  PRIMARY KEY (`staff_mail`),
  CONSTRAINT `fk_pool_staff_staff1`
    FOREIGN KEY (`staff_mail`)
    REFERENCES `mydb`.`staff` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gym_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gym_staff` (
  `staff_mail` CHAR(255) NOT NULL,
  INDEX `fk_pool_staff_staff1_idx` (`staff_mail` ASC) VISIBLE,
  PRIMARY KEY (`staff_mail`),
  CONSTRAINT `fk_pool_staff_staff10`
    FOREIGN KEY (`staff_mail`)
    REFERENCES `mydb`.`staff` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `staff_mail` CHAR(255) NOT NULL,
  INDEX `fk_pool_staff_staff1_idx` (`staff_mail` ASC) VISIBLE,
  PRIMARY KEY (`staff_mail`),
  CONSTRAINT `fk_pool_staff_staff11`
    FOREIGN KEY (`staff_mail`)
    REFERENCES `mydb`.`staff` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `content` TEXT(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organizes` (
  `staff_mail` CHAR(255) NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`staff_mail`, `event_id`),
  INDEX `fk_staff_has_event_event1_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_staff_has_event_staff1_idx` (`staff_mail` ASC) VISIBLE,
  CONSTRAINT `fk_staff_has_event_staff1`
    FOREIGN KEY (`staff_mail`)
    REFERENCES `mydb`.`staff` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_has_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timetable` (
  `mail` CHAR(255) NOT NULL,
  PRIMARY KEY (`mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sign in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sign in` (
  `members_mail` CHAR(255) NOT NULL,
  `timetable_mail` CHAR(255) NOT NULL,
  PRIMARY KEY (`members_mail`, `timetable_mail`),
  INDEX `fk_members_has_timetable_timetable1_idx` (`timetable_mail` ASC) VISIBLE,
  INDEX `fk_members_has_timetable_members1_idx` (`members_mail` ASC) VISIBLE,
  CONSTRAINT `fk_members_has_timetable_members1`
    FOREIGN KEY (`members_mail`)
    REFERENCES `mydb`.`members` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_has_timetable_timetable1`
    FOREIGN KEY (`timetable_mail`)
    REFERENCES `mydb`.`timetable` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`came_in_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`came_in_date` (
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `status` INT NOT NULL,
  `timetable_mail` CHAR(255) NOT NULL,
  PRIMARY KEY (`timetable_mail`),
  CONSTRAINT `fk_came_in_date_timetable1`
    FOREIGN KEY (`timetable_mail`)
    REFERENCES `mydb`.`timetable` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `book_time` DATETIME NOT NULL,
  `timetable_mail` CHAR(255) NOT NULL,
  PRIMARY KEY (`timetable_mail`),
  CONSTRAINT `fk_booking_timetable1`
    FOREIGN KEY (`timetable_mail`)
    REFERENCES `mydb`.`timetable` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
