CREATE TRIGGER before_delete_members BEFORE DELETE ON members FOR EACH ROW SIGNAL SQLSTATE '45000';
CREATE TRIGGER before_insert_members BEFORE INSERT ON members FOR EACH ROW SIGNAL SQLSTATE '45000';
CREATE TRIGGER before_update_members BEFORE UPDATE ON members FOR EACH ROW SIGNAL SQLSTATE '45000';

CREATE TRIGGER before_update_event BEFORE UPDATE ON event FOR EACH ROW SIGNAL SQLSTATE '45000';
CREATE TRIGGER before_insert_event BEFORE INSERT ON event FOR EACH ROW SIGNAL SQLSTATE '45000';
CREATE TRIGGER before_delete_event BEFORE DELETE ON event FOR EACH ROW SIGNAL SQLSTATE '45000';

CREATE TRIGGER before_insert_oversees BEFORE INSERT ON oversees FOR EACH ROW SIGNAL SQLSTATE '45000';
CREATE TRIGGER before_delete_oversees BEFORE DELETE ON oversees FOR EACH ROW SIGNAL SQLSTATE '45000';
CREATE TRIGGER before_update_oversees BEFORE UPDATE ON oversees FOR EACH ROW SIGNAL SQLSTATE '45000';


